spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  data:
    redis:
      host: s4.java21.net
      port: 6379
      database: 295
      password: ${REDIS_PASSWORD}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    fetch-registry: true
    register-with-eureka: true
gateway:
  whitelist:
    - path: /auth/**
      methods: [ ]
    - path: /shop/users
      methods: [ POST ]
    - path: /shop/users/social
      methods: [ POST ]
    - path: /shop/users/available
      methods: [ GET ]
    - path: /shop/guest-cart
      methods: [ ]
    - path: /shop/me/books/*/reviews
      methods: [ GET ]
    - path: /shop/books/**
      methods: [ GET ]
    - path: /shop/books/*/view
      methods: [ POST ]
    - path: /shop/books/*/search
      methods: [ POST ]
    - path: /shop/categories/tree
      methods: [ GET ]
    - path: /shop/search/**
      methods: [ GET ]
    - path: /shop/packagings/**
      methods: [ GET ]
    - path: /shop/coupons/**
      methods: [ GET ]
    - path: /shop/shipping-policies/**
      methods: [ GET ]
