spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  data:
    redis:
      host: s4.java21.net
      port: 6379
      database: 295
      password: ${REDIS_PASSWORD}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    fetch-registry: true
    register-with-eureka: true
gateway:
  whitelist:
    - /auth/**
    - /shop/users
    - /shop/users/check
    - /shop/guest-cart
    - /shop/books/*/reviews
    - /shop/books
    - /shop/books/*
    - /shop/books/category
    - /shop/books/search
