spring:
  application:
    name: ink3-eureka
  lifecycle:
    timeout-per-shutdown-phase: 10s
server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: true
    health:
      show-details: always