spring:
  config:
    import: optional:configserver:https://ink3.shop/config/
  cloud:
    bus:
      enabled: true
  rabbitmq:
    host: s4.java21.net
    port: 5672
    username: admin
    password: nhnacademy123!
    virtual-host: ink_dev
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/project_be9_team3_batch_dev?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: project_be9_team3
    password: -/jvCmf5WlFZF!U_
  batch:
    jdbc:
      initialize-schema: never
      

management:
  endpoints:
    web:
      exposure:
        include:
          - busrefresh, health, refresh
