spring:
  cloud:
    openfeign:
      okhttp:
        enabled: true
server:
  servlet:
    context-path: /auth

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: ALWAYS
    health:
      show-details: always