spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  data:
    redis:
      host: s4.java21.net
      port: 6379
      database: 295
      password: ${REDIS_PASSWORD}
jwt:
  private-key-path: ${JWT_PRIVATE_KEY_PATH}
  public-key-path: ${JWT_PUBLIC_KEY_PATH}
  access-token-validity: 1800000
  refresh-token-session-validity: 86400000
  refresh-token-validity: 2592000000
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    fetch-registry: true
    register-with-eureka: true
oauth2:
  client:
    registrations:
      payco:
        client-id: ${PAYCO_CLIENT_ID}
        client-secret: ${PAYCO_CLIENT_SECRET}
        redirect-uri: https://ink3.shop/gateway/auth/oauth2/callback/payco
        authorization-grant-type: authorization_code
        authorization-uri: https://id.payco.com/oauth2.0/authorize?serviceProviderCode=FRIENDS
        token-uri: https://id.payco.com/oauth2.0/token
        user-info-uri: https://apis-payco.krp.toastoven.net/payco/friends/find_member_v2.json
front:
  url: https://ink3.shop
