spring:
  cloud:
    openfeign:
      okhttp:
        enabled: true
server:
  servlet:
    context-path: /auth
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info
dooray:
  message-url: ${DOORAY_MESSAGE_URL}
