eureka:
  client:
    enabled: false
jwt:
  private-key-path: classpath:secret/private.pem
  public-key-path: classpath:secret/public.pem
  access-token-validity: 1800000
  refresh-token-validity: 604800000
