spring:
  cloud:
    openfeign:
      okhttp:
        enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
gateway-base-url: http://localhost:8080
feign:
  url:
    auth: ""
    shop: ""


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: ALWAYS
    health:
      show-details: ALWAYS