gateway-base-url: https://ink3.shop/dev/gateway
server:
  servlet:
    context-path: /dev
feign:
  url:
    auth: https://ink3.shop/dev/gateway/auth
    shop: https://ink3.shop/dev/gateway/shop
auth:
  protected-paths:
    - /me/*
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

