gateway-base-url: https://ink3.shop/dev/gateway
server:
  servlet:
    context-path: /dev
feign:
  url:
    gateway: http://127.0.0.1:10265
    auth: http://127.0.0.1:10265/auth
    shop: http://127.0.0.1:10265/shop
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

