app:
  name: Spring cloud config
  version: 0.0.1

server:
  port: 10260

api:
  message: localtest
  profile:
    active:
      message: config test

management:
  endpoint:
    env:
      show-values: ALWAYS

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


