
payment:
  toss:
    client_key : "temp"
    secret_key : "temp"
    confirm_url : "https://api.tosspayments.com/v1/payments/confirm"
    success_url : "http://localhost:8080/payment/success"
    fail_url : "http://localhost:8080/payment/fail"

server:
  servlet:
    context-path: /shop

aladin:
  ttb-key: ${TTB_KEY}


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: true
    health:
      show-details: ALWAYS