payment:
  toss:
    client_key: ${TOSS_PAYMENT_CLIENT_KEY}
    secret_key: ${TOSS_PAYMENT_SECRET_KEY}
    confirm_url: "https://api.tosspayments.com/v1/payments/confirm"
server:
  servlet:
    context-path: /shop
aladin:
  ttb-key: ${TTB_KEY}
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info
