spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://s4.java21.net:13306/project_be9_team3_dev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: s4.java21.net
      port: 6379
      database: 297
      password: ${REDIS_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    hibernate:
      ddl-auto: validate
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL}
minio:
  host: ${MINIO_HOST}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  review-bucket: ink3-dev-reviews-images
  book-bucket: ink3-dev-books-images
